services:
  - type: web
    name: elearning-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: REACT_APP_API_BASE
        value: https://e-learning-backend-5rau.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
